float32 distance                       # Distance to the center
geometry_msgs/Vector3 position_vec     # Center 3D position (X,Y,Z)
geometry_msgs/Vector3 orientation_vec  # Orientation angles (Roll, Pitch, Yaw)
geometry_msgs/Vector3 pixel_vec        # Center Pixel coordinates (x, y, 0)

geometry_msgs/Vector3 pixel_top_left
geometry_msgs/Vector3 pixel_top_right
geometry_msgs/Vector3 pixel_bottom_right
geometry_msgs/Vector3 pixel_bottom_left