objects:
  0:
    name: "gate"
    points:
      - [0.0, 0.0, 0.0]
      - [0.385, 0.0, 0.0]
      - [0.250, 0.408, 0.0]
      - [0.050, 0.408, 0.0]
  1:
    name: "torpedo"
    points:
      - [0.0, 0.0, 0.0]
      - [0.6, 0.0, 0.0]
      - [0.6, 0.6, 0.0]
      - [0.0, 0.6, 0.0]
  2:
    name: "buoy"
    points:
      - [0.0, 0.0, 0.0]
      - [0.3, 0.0, 0.0]
      - [0.3, 0.3, 0.0]
      - [0.0, 0.3, 0.0]
  3:
    name: "bin"
    points:
      - [0.0, 0.0, 0.0]
      - [0.6, 0.0, 0.0]
      - [0.6, 0.6, 0.0]
      - [0.0, 0.6, 0.0]
